# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
