# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
    ]
