# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
