# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('has_dev_perm', 'Has dev permissions'),)},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
