# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 15:02
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_repo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_tarball',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/apps'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='licences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_page',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
