# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180403_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
