# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180405_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='version_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
