# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180406_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='storage_flash_support',
            field=models.BooleanField(default=False),
        ),
    ]
