# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_board_storage_flash_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1),
        ),
    ]
