# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='licences',
            new_name='licenses',
        ),
    ]
