# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180430_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('R', 'RIOT_REPO'), ('E', 'EXTERNAL')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[-\\w_]+$', code='Invalid name', message='Name must be alphanumeric, hyphen or underscore only. No spaces allowed')]),
        ),
    ]
