# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180508_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='app_tarball_md5',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
