# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180507_1450'),
        ('api', '0021_auto_20180508_2311'),
    ]

    operations = [
    ]
