# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20180509_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
