# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 11:30
from __future__ import unicode_literals

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    model = apps.get_model('api', 'ApplicationInstance')
    for row in model.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_applicationinstance_uuid'),
    ]

    operations = [
            migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
