# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180612_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
