# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180612_1130'),
    ]

    operations = [
        migrations.RemoveField('ApplicationInstance', 'id'),
        migrations.RenameField(
            model_name='ApplicationInstance',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='ApplicationInstance',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False,  unique=True),
),
    ]
