# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180612_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
