# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='elf_file',
            new_name='app_folder',
        ),
        migrations.AddField(
            model_name='application',
            name='app_repo_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='licences',
            field=models.CharField(default='nolicense', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='project_page',
            field=models.URLField(default='project_page_url', max_length=255),
            preserve_default=False,
        ),
    ]
