# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 13:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20180309_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_tarball',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/apps'), upload_to=''),
        ),
    ]
