# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20180312_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='author',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
