# -*- coding: UTF-8 -*-

"""
 * Copyright (C) 2018 FU Berlin and HAW Hamburg
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
"""

# items without indention mean: "no explicit information found about this feature"

internalname_storageflashsupport_dict = {
    'acd52832': True,
'airfy-beacon': False,
'arduino-due': False,
'arduino-duemilanove': False,
'arduino-mega2560': False,
'arduino-mkr1000': False,
'arduino-mkrzero': False,
'arduino-uno': False,
'arduino-zero': False,
'avsextrem': False,
'b-l072z-lrwan1': True,
'b-l475e-iot01a': False,
    'bluepill': True,
'calliope-mini': False,
'cc2538dk': False,
'cc2650-launchpad': False,
'cc2650stk': False,
'chronos': False,
'ek-lm4f120xl': False,
'f4vi1': False,
'feather-m0': False,
'fox': False,
    'frdm-k22f': True,
    'frdm-k64f': True,
'ikea-tradfri': False,
'iotlab-a8-m3': False,
'iotlab-m3': False,
'limifrog-v1': False,
    'maple-mini': True,
    'mbed_lpc1768': True,
'microbit': False,
'mips-malta': False,
'msb-430': False,
'msb-430h': False,
'msba2': False,
'msbiot': False,
'mulle': False,
    'nrf51dongle': True,
    'nrf52840dk': True,
    'nrf52dk': True,
    'nrf6310': True,
    'nucleo-f030': True,
    'nucleo-f070': True,
    'nucleo-f072': True,
    'nucleo-f091': True,
    'nucleo-f103': True,
    'nucleo-f302': True,
    'nucleo-f303': True,
    'nucleo-f334': True,
    'nucleo-f401': True,
    'nucleo-f410': True,
    'nucleo-f411re': True,
    'nucleo-f446': True,
    'nucleo-l053': True,
    'nucleo-l073': True,
    'nucleo-l152re': True,
    'nucleo-l476': True,
    'nucleo144-f207': True,
    'nucleo144-f303': True,
    'nucleo144-f412': True,
    'nucleo144-f413': True,
    'nucleo144-f429': True,
    'nucleo144-f446': True,
    'nucleo144-f722': True,
    'nucleo144-f746': True,
    'nucleo144-f767': True,
    'nucleo32-f031': True,
    'nucleo32-f042': True,
    'nucleo32-f303': True,
    'nucleo32-l031': True,
    'nucleo32-l432': True,
    'nz32-sc151': True,
'opencm904': False,
'openmote-cc2538': False,
'pba-d-01-kw2x': True,
'pca10000': False,
'pca10005': False,
'pic32-clicker': False,
'pic32-wifire': False,
'qemu-i386': False,
'remote-pa': False,
'remote-reva': False,
'remote-revb': False,
'ruuvitag': False,
    'samd21-xpro': False,
    'saml21-xpro': False,
    'samr21-xpro': False,
    'seeeduino_arch-pro': True,
'sltb001a': False,
'slwstk6220a': False,
'sodaq-autonomo': False,
'sodaq-explorer': False,
'spark-core': False,
    'stm32f0discovery': True,
    'stm32f3discovery': True,
    'stm32f4discovery': True,
    'stm32f7discovery': True,
'telosb': False,
'thingy52': False,
'udoo': False,
'waspmote-pro': False,
'wsn430-v1_3b': False,
'wsn430-v1_4': False,
'yunjia-nrf51822': False,
'z1': False,
}
